server_name localhost;
root /var/www/public;
index index.php index.html index.htm;

# Default redirects
rewrite ^/(.*)/$ /$1 permanent;
rewrite ^/index.(html|php)$ / permanent;

# Clickjacking
add_header Content-Security-Policy $ContentSecurityPolicy;

# HSTS
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# Disable executing PHP scripts in uploads and violations folders
location ^~ /uploads/ {
    auth_basic off;
    expires     1y;
}

# Cache static file (images for 1 year, styles and scripts for 1 week)
location ~* ^/assets/.*\.(gif|ico|jpe?g|png)(\?[0-9]+)?$ {
    auth_basic off;
    expires     1y;
}

location ~* ^/account/.*\.(gif|ico|jpe?g|png|svg|woff2?)(\?[0-9]+)?$ {
    expires     1y;
    auth_basic off;
}

location ~* ^/account/.*\.(eot|otf|svg|ttf|woff|woff2)(\?[0-9]+)?$ {
    expires 1y;
    auth_basic off;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "public";
    add_header Pragma public;
}

# Redirect assets for CDN
location ~* ^/assets/(?<folder>css|js)_(?<id>[\w\d]+)/(?<file>.+)$ {
    auth_basic off;
    try_files $uri /assets/$folder/$file?id=$id;
}

location ~* ^/assets/.*\.(css|js)$ {
    expires     1w;
    auth_basic off;
}

location ~* ^/assets/.*\.(eot|otf|svg|ttf|woff|woff2)(\?[0-9]+)?$ {
    expires 1y;
    auth_basic off;
    add_header Access-Control-Allow-Origin *;
    add_header Cache-Control "public";
    add_header Pragma public;
}

# Laravel with caching
location / {
    # Меняем root, чтобы иметь возможность посмотреть в папку "storage"
    root /var/www/;

    set $cache_file /storage/page-cache/${request_method}_$md5_uri.html;
    if (-f $document_root$cache_file$cookie_guest) {
        # Запрещаем браузеру кэшировать эту страницу
        add_header Cache-Control no-cache;
        expires epoch;

        # Clickjacking
        add_header Content-Security-Policy $ContentSecurityPolicy;

        # HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # Перенаправляем ответ на кэш
        rewrite .* $cache_file break;
    }

    rewrite ^/index.php/(.*) /$1  permanent;

    # Ищем сначала закешированную версию страницы, потом существующий файл и только потом перенаправляем на ларавел
    try_files /public/$uri /public/index.php$is_args$args;
}

location ~ \.php$ {
    include /etc/nginx/sites-available/defaults/php.conf;
}
