user www-data;
worker_processes 4;
pid /run/nginx.pid;
daemon off;
load_module "modules/ngx_http_perl_module.so";

events {
  worker_connections  2048;
  multi_accept on;
  use epoll;
}

http {
  include /etc/nginx/conf.d/http.conf;
}
